#cmakedefine01 KAUTH_COMPILING_FAKE_BACKEND
#define KAUTH_BACKEND_PLUGIN_DIR "${CMAKE_INSTALL_PREFIX}/${PLUGIN_INSTALL_DIR}/${KAUTH_BACKEND_PLUGIN_DIR}"
#define KAUTH_HELPER_PLUGIN_DIR "${CMAKE_INSTALL_PREFIX}/${PLUGIN_INSTALL_DIR}/${KAUTH_HELPER_PLUGIN_DIR}"
